services:
  - type: web
    name: cyber-monitor
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: WKHTMLTOPDF_PATH
        value: /usr/bin/wkhtmltopdf
