services:
  - type: web
    name: cyber_project
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
